In [5]:
import numpy as np
arr_1d=np.arange(10,51)
print(arr_1d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [6]:
arr=np.random.random((3,3))
print(arr)

[[0.14428648 0.61606764 0.7191481 ]
 [0.34966487 0.26014515 0.95949397]
 [0.83125539 0.2958974  0.44786156]]


In [7]:
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 3)
9
float64
2


In [8]:
arr_1d=np.array([1,2,3])
print(arr_1d+5)

[6 7 8]


In [10]:
 arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1*arr2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [20]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [24]:
print(arr[0,:])

[1 2 3 4 5]


In [25]:
print(arr[:,-1])

[ 5 10 15 20 25]


In [26]:
print(arr[:3,:2])

[[ 1  2]
 [ 6  7]
 [11 12]]


In [28]:
arr = np.random.randint(1, 101, size=10)
print(arr)


[57 28 15 96 55 24 25 51 21 16]


In [30]:
print("mean:\t",np.mean(arr1))
print("std:\t",np.std(arr1))
print("max:\t",np.max(arr1))
print("min:\t",np.min(arr1))

mean:	 5.0
std:	 2.581988897471611
max:	 9
min:	 1


In [31]:
arr = np.arange(1, 13)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
zeroes=np.ones((3,3))
arr_1d=np.array([1,2,3])
print(zeroes+arr_1d)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [46]:
arr = np.random.randint(1, 51, size=10)
print(arr)
arr_5=arr[arr%5==0]
print(arr_5)


[19 39 17 17  5  2 23 43 48 26]
[5]


In [49]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = a @ b
print(result)


[[19 22]
 [43 50]]


In [ ]:
import numpy as np

# Create a 4x4 array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# Extract diagonal elements using fancy indexing
diagonal_elements = array[[0, 1, 2, 3], [0, 1, 2, 3]]

print("Array:")
print(array)
print("\nDiagonal Elements:")
print(diagonal_elements)
